### ISSUE TITLE
Spotify segfaults eventd

### ISSUE THREAD

**Issue by AhmedAA** [p3lim/dotfiles#1]
Hey!

First of all, I spent a lot of time trying to find "the perfect" bar and setup to use in multi WM environments, but couldn't find anything suitable..

Then I found your post on /r/unixporn and I was baffled by the way you have gone about solving this issue. Good job!

To the issue:
I have more or less cloned your `eventd` setup, and I am actually quite happy with it. One issue though, as stated in the title, if I change songs (approximately 3 or 4 times in a row quickly), I segfault `eventd` and it just dies.

I think it successfully restarts (according to your scripts), but it does not attach to the correct display.

Do you have any tips?

Cheers :)

**Comment by p3lim** [comment]
I think you're better off posting this on [eventd's repo](https://github.com/sardemff7/eventd) instead, and also maybe joining #eventd on freenode, the author is quite active there.

Also, I'm basing my config off the master branch, I doubt it'd work on the stable version.

**Comment by AhmedAA** [comment]
solved upstream, has nothing to do with the configs here!
