### ISSUE TITLE
How to set up the notification system

### ISSUE THREAD

**Issue by vsr625** [p3lim/dotfiles#2]
Hey, cool config. I'm trying to replicate the notification system from your config, but after installing eventd and copying your config files from .config/eventd/ directory, no notifications are being displayed. I tried checking by doing a systemctl --user status eventd. The eventd is capturing the events, but no notification is being displayed. 
Can you help me out by telling how to properly set up the notification system?

**Comment by p3lim** [comment]
Make sure your DISPLAY env is set correctly, and that eventd properly runs (you're best off restarting to be sure after the installation, or following the manual to start the required services with systemd).

If you need any dedicated help, the author of eventd is very active on #eventd @ freenode, he'll be able to assist you for sure.
